// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: annonce.sql

package database

import (
	"context"
)

const getAnnonces = `-- name: GetAnnonces :many
SELECT id, user_id, message, created_at, updated_at FROM annonces
`

func (q *Queries) GetAnnonces(ctx context.Context) ([]Annonce, error) {
	rows, err := q.query(ctx, q.getAnnoncesStmt, getAnnonces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Annonce
	for rows.Next() {
		var i Annonce
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
