// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: evenement.sql

// Package database gère la connexion à la base de données et les requêtes.
package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const newEvent = `-- name: NewEvent :exec
INSERT INTO 
evenements (nom, description, debut_vente, fin_vente, organisateur, heure_evenement, location_evenement, chemin_photo, categorie, prix_billet, quantite_billet)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type NewEventParams struct {
	Nom               pgtype.Text      `json:"nom"`
	Description       string           `json:"description"`
	DebutVente        pgtype.Date      `json:"debut_vente"`
	FinVente          pgtype.Date      `json:"fin_vente"`
	Organisateur      int64            `json:"organisateur"`
	HeureEvenement    pgtype.Timestamp `json:"heure_evenement"`
	LocationEvenement pgtype.Text      `json:"location_evenement"`
	CheminPhoto       pgtype.Text      `json:"chemin_photo"`
	Categorie         pgtype.Text      `json:"categorie"`
	PrixBillet        pgtype.Float8    `json:"prix_billet"`
	QuantiteBillet    pgtype.Int4      `json:"quantite_billet"`
}

func (q *Queries) NewEvent(ctx context.Context, arg NewEventParams) error {
	_, err := q.db.Exec(ctx, newEvent,
		arg.Nom,
		arg.Description,
		arg.DebutVente,
		arg.FinVente,
		arg.Organisateur,
		arg.HeureEvenement,
		arg.LocationEvenement,
		arg.CheminPhoto,
		arg.Categorie,
		arg.PrixBillet,
		arg.QuantiteBillet,
	)
	return err
}
