// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Evenement struct {
	ID            uint64         `json:"id"`
	Nom           sql.NullString `json:"nom"`
	Description   string         `json:"description"`
	DebutVente    time.Time      `json:"debut_vente"`
	FinVente      time.Time      `json:"fin_vente"`
	DateEvenement time.Time      `json:"date_evenement"`
	Organisateur  uint64         `json:"organisateur"`
}

type User struct {
	ID           uint64         `json:"id"`
	Nom          sql.NullString `json:"nom"`
	Postnom      sql.NullString `json:"postnom"`
	Prenom       sql.NullString `json:"prenom"`
	Email        sql.NullString `json:"email"`
	TypeCompte   sql.NullString `json:"type_compte"`
	PasswordHash sql.NullString `json:"password_hash"`
}
