// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Evenement struct {
	ID                int64            `json:"id"`
	Nom               pgtype.Text      `json:"nom"`
	Description       string           `json:"description"`
	DebutVente        pgtype.Date      `json:"debut_vente"`
	FinVente          pgtype.Date      `json:"fin_vente"`
	DateEvenement     pgtype.Date      `json:"date_evenement"`
	Organisateur      int64            `json:"organisateur"`
	HeureEvenement    pgtype.Timestamp `json:"heure_evenement"`
	LocationEvenement pgtype.Text      `json:"location_evenement"`
	CheminPhoto       pgtype.Text      `json:"chemin_photo"`
	Categorie         pgtype.Text      `json:"categorie"`
	PrixBillet        pgtype.Float8    `json:"prix_billet"`
	QuantiteBillet    pgtype.Int4      `json:"quantite_billet"`
}

type User struct {
	ID           int64       `json:"id"`
	Nom          pgtype.Text `json:"nom"`
	Prenom       pgtype.Text `json:"prenom"`
	Email        pgtype.Text `json:"email"`
	TypeCompte   pgtype.Text `json:"type_compte"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Pseudonyme   pgtype.Text `json:"pseudonyme"`
	Description  pgtype.Text `json:"description"`
	CheminPhoto  pgtype.Text `json:"chemin_photo"`
}
