// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package database

import (
	"context"
	"database/sql"
)

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password_hash from users WHERE email = ?
`

func (q *Queries) GetPasswordHash(ctx context.Context, email sql.NullString) (sql.NullString, error) {
	row := q.queryRow(ctx, q.getPasswordHashStmt, getPasswordHash, email)
	var password_hash sql.NullString
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, nom, postnom, prenom, email, type_compte, password_hash from users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nom,
		&i.Postnom,
		&i.Prenom,
		&i.Email,
		&i.TypeCompte,
		&i.PasswordHash,
	)
	return i, err
}

const getUserId = `-- name: GetUserId :one
SELECT id, nom, postnom, prenom, email, type_compte, password_hash from users WHERE id = ?
`

func (q *Queries) GetUserId(ctx context.Context, id uint64) (User, error) {
	row := q.queryRow(ctx, q.getUserIdStmt, getUserId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nom,
		&i.Postnom,
		&i.Prenom,
		&i.Email,
		&i.TypeCompte,
		&i.PasswordHash,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, nom, postnom, prenom, email, type_compte, password_hash from users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.getUsersStmt, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nom,
			&i.Postnom,
			&i.Prenom,
			&i.Email,
			&i.TypeCompte,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUser = `-- name: NewUser :exec
INSERT INTO users (nom, postnom, prenom, email, password_hash)
VALUES(?, ?, ?, ?, ?)
`

type NewUserParams struct {
	Nom          sql.NullString `json:"nom"`
	Postnom      sql.NullString `json:"postnom"`
	Prenom       sql.NullString `json:"prenom"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) error {
	_, err := q.exec(ctx, q.newUserStmt, newUser,
		arg.Nom,
		arg.Postnom,
		arg.Prenom,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}
