// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/dstm45/seed/pkg/views/component"

func ChangePassword() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"max-w-3xl mx-auto px-6 py-12\"><div class=\"bg-white shadow rounded-lg p-8\"><h1 class=\"text-2xl font-bold text-gray-800 mb-6\">Change Password</h1><form action=\"/profile/change-password\" method=\"POST\" class=\"space-y-6\"><!-- Current Password --><div><label for=\"currentPassword\" class=\"block text-gray-700 font-medium\">Current Password</label> <input type=\"password\" id=\"currentPassword\" name=\"currentPassword\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\" placeholder=\"••••••••\"></div><!-- New Password --><div><label for=\"newPassword\" class=\"block text-gray-700 font-medium\">New Password</label> <input type=\"password\" id=\"newPassword\" name=\"newPassword\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\" placeholder=\"••••••••\"></div><!-- Confirm New Password --><div><label for=\"confirmPassword\" class=\"block text-gray-700 font-medium\">Confirm New Password</label> <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\" placeholder=\"••••••••\"></div><!-- Back to Profile Link --><div class=\"text-right\"><a href=\"/profile/edit\" class=\"text-red-500 font-medium hover:underline\">Back to Profile</a></div><!-- Submit Button --><button type=\"submit\" class=\"w-full bg-gradient-to-r from-purple-600 via-pink-500 to-red-500 text-white font-bold py-3 rounded-full hover:opacity-90 transition\">Update Password</button></form></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = component.Base("", "change password").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
