// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/dstm45/seed/pkg/database"

func EditUser(utilisateur database.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Edit Profile | EventHub</title><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-gray-50\"><!-- Header --><header class=\"relative overflow-hidden bg-gradient-to-r from-purple-600 via-pink-500 to-red-500 text-white\"><div class=\"relative z-10 max-w-7xl mx-auto px-6 py-6 md:py-8 flex flex-col md:flex-row justify-between items-center\"><a href=\"/\" class=\"text-3xl font-extrabold tracking-wide hover:scale-105 transition-transform duration-300\">EventHub</a><nav class=\"mt-4 md:mt-0\"><ul class=\"flex space-x-8 items-center text-lg\"><li><a href=\"#concerts\" class=\"hover:text-gray-200\">Concerts</a></li><li><a href=\"#shows\" class=\"hover:text-gray-200\">Shows</a></li><li><a href=\"#seminars\" class=\"hover:text-gray-200\">Seminars</a></li><li><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL("/logout"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 26, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"hover:text-gray-200\">Se déconnecter</a></li></ul></nav><a href=\"/buy-tickets\" class=\"mt-4 md:mt-0 bg-white text-red-500 font-bold py-2 px-6 rounded-full shadow-lg hover:bg-gray-200 transition-all duration-300\">Buy Tickets</a></div><div class=\"absolute right-0 bottom-0 md:bottom-10 opacity-70 float-animation\"><svg class=\"w-32 h-32 md:w-48 md:h-48\" viewBox=\"0 0 200 200\"><path fill=\"#FFCDD2\" d=\"M42.3,-64.2C55.8,-56.7,67.8,-44.3,72.8,-29.3C77.8,-14.4,75.8,2.3,70.7,17.5C65.7,32.7,57.7,46.4,46.8,54.5C35.9,62.6,22.1,65.1,7.5,68.4C-7.1,71.7,-21.8,75.9,-34.3,73.3C-46.7,70.8,-57,61.4,-65.3,49.8C-73.6,38.2,-79.8,24.4,-83.2,9.9C-86.6,-4.6,-87.2,-20.8,-80.2,-33.9C-73.2,-47,-58.7,-57,-43.1,-64.7C-27.5,-72.4,-13.8,-77.7,1.6,-80.6C17,-83.4,34,-84.2,42.3,-64.2Z\" transform=\"translate(100 100)\"></path></svg></div><div class=\"absolute inset-0 bg-black opacity-20\"></div></header><!-- Main Content --><main class=\"max-w-3xl mx-auto px-6 py-12\"><div class=\"bg-white shadow rounded-lg p-8\"><h1 class=\"text-2xl font-bold text-gray-800 mb-6\">Edit Your Profile</h1><form action=\"/editprofile\" method=\"POST\" enctype=\"multipart/form-data\" class=\"space-y-6\"><!-- Profile Photo Upload (unchanged) --><div class=\"flex items-center space-x-6\"><img id=\"avatarPreview\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(utilisateur.CheminPhoto.String)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 49, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" alt=\"Profile Photo\" class=\"w-24 h-24 rounded-full border-4 border-red-500 object-cover\"><div class=\"space-y-2\"><input type=\"file\" id=\"avatar\" name=\"avatar\" accept=\"image/*\" class=\"hidden\"> <label for=\"avatar\" class=\"inline-flex items-center px-4 py-2 bg-white text-gray-700 border border-gray-300 rounded-lg shadow-sm hover:bg-gray-100 cursor-pointer transition\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"w-5 h-5 mr-2 text-gray-500\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 7h4l2-3h6l2 3h4v11a2 2 0 01-2 2H5a2 2 0 01-2-2z\"></path> <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 11a3 3 0 100 6 3 3 0 000-6z\"></path></svg> Choisir un fichier</label><p id=\"fileName\" class=\"text-sm text-gray-500\">Aucun fichier choisi</p></div></div><!-- New Form Fields -->Image invalide\t\t\t\t\t<div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><!-- Nom --><div><label for=\"nom\" class=\"block text-gray-700 font-medium\">Nom</label> <input type=\"text\" id=\"nom\" name=\"nom\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(utilisateur.Nom.String)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 91, Col: 39}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\"></div><!-- Prénom --><div><label for=\"prenom\" class=\"block text-gray-700 font-medium\">Prénom</label> <input type=\"text\" id=\"prenom\" name=\"prenom\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(utilisateur.Prenom.String)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 103, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\"></div></div><!-- Nom d'utilisateur --><div><label for=\"username\" class=\"block text-gray-700 font-medium\">Nom d’utilisateur</label> <input type=\"text\" id=\"username\" name=\"username\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(utilisateur.Pseudonyme.String)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 116, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\"></div><!-- Email --><div><label for=\"email\" class=\"block text-gray-700 font-medium\">Email Address</label> <input type=\"email\" id=\"email\" name=\"email\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(utilisateur.Email.String)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 128, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" required class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\"></div><!-- Description --><div><label for=\"description\" class=\"block text-gray-700 font-medium\">À propos de vous</label> <textarea id=\"description\" name=\"description\" rows=\"4\" class=\"mt-1 w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-red-500\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(utilisateur.Description.String)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/user/editUser.templ`, Line: 141, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" placeholder=\"Parlez de vous\"></textarea></div><!-- Change Password Link --><div class=\"text-right\"><a href=\"/editpassword\" class=\"text-red-500 font-medium hover:underline\">Change Password</a></div><!-- Submit Button --><button type=\"submit\" class=\"w-full bg-gradient-to-r from-purple-600 via-pink-500 to-red-500 text-white font-bold py-3 rounded-full hover:opacity-90 transition\">Save Changes</button></form></div></main><!-- Preview & Filename Script (unchanged) --><script>\n    \t\tconst input = document.getElementById('avatar');\n    \t\tconst preview = document.getElementById('avatarPreview');\n    \t\tconst fileName = document.getElementById('fileName');\n\n    \t\tinput.addEventListener('change', e => {\n      \t\tconst file = e.target.files[0];\n      \t\tif (!file) return;\n      \t\tpreview.src = URL.createObjectURL(file);\n      \t\tfileName.textContent = file.name.length > 20\n        \t? file.name.slice(0, 17) + '…'\n        \t: file.name;\n    \t\t});\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
