// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package evenement

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/dstm45/seed/pkg/database"
	"github.com/dstm45/seed/pkg/views/component"
)

func Evenement(evenement database.Evenement) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12\"><div class=\"bg-white shadow-xl rounded-lg overflow-hidden\"><div class=\"grid grid-cols-1 md:grid-cols-3\"><!-- Left side: Poster & Details --><div class=\"md:col-span-1 p-6 md:p-8\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(evenement.CheminPhoto.String)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/evenement/evenement.templ`, Line: 15, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" alt=\"Event Poster\" class=\"rounded-lg shadow-lg w-full mb-8\"><div class=\"bg-gray-50 p-6 rounded-lg shadow-inner\"><h2 class=\"text-2xl font-bold text-gray-800 mb-4 border-b pb-2\">Détails</h2><div class=\"space-y-4\"><div class=\"flex items-center\"><i class=\"fas fa-calendar-alt fa-fw text-purple-600 mr-3\"></i><div><p class=\"font-semibold\">Date</p><p class=\"text-gray-600\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(evenement.DateEvenement.Time.Format("02 January 2006"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/evenement/evenement.templ`, Line: 23, Col: 97}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div></div><div class=\"flex items-center\"><i class=\"fas fa-clock fa-fw text-purple-600 mr-3\"></i><div><p class=\"font-semibold\">Heure</p><p class=\"text-gray-600\">18:00 - 23:00</p></div></div><div class=\"flex items-center\"><i class=\"fas fa-map-marker-alt fa-fw text-purple-600 mr-3\"></i><div><p class=\"font-semibold\">Lieu</p><p class=\"text-gray-600\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(evenement.LocationEvenement.String)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/evenement/evenement.templ`, Line: 37, Col: 77}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div></div><div class=\"flex items-center\"><i class=\"fas fa-dollar-sign fa-fw text-purple-600 mr-3\"></i><div><p class=\"font-semibold\">Prix</p><p class=\"text-gray-600\">$25.00</p></div></div><div class=\"flex items-center\"><i class=\"fas fa-chair fa-fw text-purple-600 mr-3\"></i><div><p class=\"font-semibold\">Places Disponibles</p><p class=\"text-gray-600\">150 / 500</p></div></div></div></div><div class=\"mt-8\"><h3 class=\"text-xl font-bold text-gray-800 mb-4\">Calendrier</h3><div class=\"bg-white p-4 rounded-lg shadow\"><div class=\"flex items-center justify-between mb-4\"><button class=\"text-gray-600 hover:text-purple-600\"><i class=\"fas fa-chevron-left\"></i></button><h4 class=\"font-semibold\">Juillet 2025</h4><button class=\"text-gray-600 hover:text-purple-600\"><i class=\"fas fa-chevron-right\"></i></button></div><div class=\"grid grid-cols-7 gap-2 text-center text-sm\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = component.Calendrier().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></div></div><!-- Right side: Title, Description, Map --><div class=\"md:col-span-2 p-6 md:p-8\"><h1 class=\"text-4xl font-extrabold text-gray-900 mb-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(evenement.Nom.String)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/evenement/evenement.templ`, Line: 76, Col: 85}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h1><div class=\"flex items-center text-gray-500 mb-6\"><i class=\"fas fa-tag mr-2\"></i> <span>Catégorie de l'événement</span></div><h2 class=\"text-2xl font-bold text-gray-800 mb-4 border-b pb-2\">Description</h2><p class=\"text-gray-700 leading-relaxed\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(evenement.Description)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/views/evenement/evenement.templ`, Line: 83, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p><h2 class=\"text-2xl font-bold text-gray-800 mt-8 mb-4 border-b pb-2\">Localisation</h2><div id=\"map\" class=\"w-full z-0\"></div></div></div></div></main><script>\n  // Coordonnées placeholder pour Kinshasa\n  const eventLatitude = -4.325;\n  const eventLongitude = 15.3222;\n\n  // Initialiser la carte\n  const map = L.map('map').setView([eventLatitude, eventLongitude], 13);\n\n  // Ajouter la couche de tuiles OpenStreetMap\n  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {\n    maxZoom: 19,\n    attribution: '© OpenStreetMap contributors'\n  }).addTo(map);\n\n  // Ajouter un marqueur pour l'événement\n  const marker = L.marker([eventLatitude, eventLongitude]).addTo(map);\n  marker.bindPopup(\"<b>Nom de l'Événement</b><br>Stade des Martyrs\").openPopup();\n</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = component.Base("", evenement.Nom.String).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
