-- +goose Up
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(45),
    postnom VARCHAR(45),
    prenom VARCHAR(45),
    type_compte VARCHAR(20),
    id_region INT,
    id_stock INT
);

CREATE TABLE IF NOT EXISTS produits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(45),
    id_agriculteur INT
);

CREATE TABLE IF NOT EXISTS stock (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS champs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS regions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS marches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50),
    id_region INT
);

CREATE TABLE IF NOT EXISTS commandes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_produit INT,
    id_client INT
);

-- +goose Down
DROP TABLE users;
DROP TABLE marches;
DROP TABLE commandes;
DROP TABLE champs;
DROP TABLE regions;
DROP TABLE produits;
DROP TABLE stock;